### ISSUE TITLE
Unable to retrieve yield data 

### ISSUE THREAD

**Issue by djaiswal** [ebimodeling/betydb_manuscript#1]
https://github.com/ebimodeling/betydb_manuscript/blob/76029818df4a988160cbb320e81b84aa218ed330/fig4a_with_ropensci_traits_package.Rmd#L40

<img width="1440" alt="Screenshot 2022-09-24 at 7 12 04 PM" src="https://user-images.githubusercontent.com/6233112/192101279-4cd7e112-250a-4913-9628-c9f8aabac22c.png">

**Comment by djaiswal** [comment]
@dlebauer I have received an error. I have shared screenshot.

**Comment by dlebauer** [comment]
Thanks for reporting this! 

For some reason the betydb url needs a www prepended

```
options(betydb_url = 'https://www.betydb.org/',
        betydb_api_version = 'v1') 
```

I have also updated the code to combine 'row_spacing', 'planting (plants / m2)' with 'planting'. 

See if this works: https://gist.github.com/dlebauer/b8a1f873e08e27aed1877d15d97e821c
